linux:
	if [ ! -d VoxLogicA_0.6.0_linux-x64 ]; then unzip VoxLogicA_0.6.0_linux-x64.zip; fi			
	VOXLOGICA=VoxLogicA_0.6.0_linux-x64/VoxLogicA ./run_analysis.sh DATASETS/data_first10 SPECIFICATION/nevusSegm_V15_2021_01_12_19H00_nevSegV0_FINAL.imgql

osx:
	if [ ! -d VoxLogicA_0.6.0_osx-x64 ]; then unzip VoxLogicA_0.6.0_linux-x64.zip; fi			
	VOXLOGICA=VoxLogicA_0.6.0_osx-x64/VoxLogicA ./run_analysis.sh DATASETS/data_first10 SPECIFICATION/nevusSegm_V15_2021_01_12_19H00_nevSegV0_FINAL.imgql
